apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-events-pod-list-create-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - update